// mealplanrecipes.mjs  

export const recipes = [  
    {  
        label: "Vegan Tacos",  
        ingredients: ["Tortillas", "Black beans", "Avocado", "Tomatoes"],  
        diet: "vegan",  
        preparationTime: "20 minutes",  
        servings: 2,  
    },  
    {  
        label: "Keto Salad",  
        ingredients: ["Lettuce", "Olive oil", "Cheese", "Chicken"],  
        diet: "keto",  
        preparationTime: "10 minutes",  
        servings: 2,  
    },  
    {  
        label: "Vegetarian Stir Fry",  
        ingredients: ["Vegetables", "Soy sauce", "Rice"],  
        diet: "vegetarian",  
        preparationTime: "15 minutes",  
        servings: 4,  
    },  
    {  
        label: "Paleo Chili",  
        ingredients: ["Beef", "Tomatoes", "Beans"],  
        diet: "paleo",  
        preparationTime: "1 hour",  
        servings: 6,  
    },  
    {  
        label: "Gluten-Free Pasta",  
        ingredients: ["Gluten-free pasta", "Tomato sauce", "Basil"],  
        diet: "gluten-free",  
        preparationTime: "30 minutes",  
        servings: 4,  
    },  
    {  
        label: "Quinoa Salad",  
        ingredients: ["Quinoa", "Cucumbers", "Feta", "Olive oil"],  
        diet: "vegetarian",  
        preparationTime: "25 minutes",  
        servings: 4,  
    },  
    {  
        label: "Zucchini Noodles",  
        ingredients: ["Zucchini", "Garlic", "Olive oil", "Parmesan"],  
        diet: "keto",  
        preparationTime: "15 minutes",  
        servings: 2,  
    },  
    {  
        label: "Stuffed Peppers",  
        ingredients: ["Bell peppers", "Rice", "Ground turkey", "Cheese"],  
        diet: "paleo",  
        preparationTime: "40 minutes",  
        servings: 4,  
    },  
    {  
        label: "Chickpea Curry",  
        ingredients: ["Chickpeas", "Coconut milk", "Curry powder", "Spinach"],  
        diet: "vegan",  
        preparationTime: "30 minutes",  
        servings: 3,  
    },  
    {  
        label: "Eggplant Parmesan",  
        ingredients: ["Eggplant", "Marinara sauce", "Mozzarella", "Basil"],  
        diet: "vegetarian",  
        preparationTime: "1 hour",  
        servings: 4,  
    },  
    {  
        label: "Keto Cauliflower Fried Rice",  
        ingredients: ["Cauliflower", "Peas", "Carrots", "Eggs"],  
        diet: "keto",  
        preparationTime: "20 minutes",  
        servings: 2,  
    },  
    {  
        label: "Paleo Chicken Stir Fry",  
        ingredients: ["Chicken", "Broccoli", "Bell peppers", "Soy sauce"],  
        diet: "paleo",  
        preparationTime: "25 minutes",  
        servings: 4,  
    },  
    {  
        label: "Gluten-Free Pancakes",  
        ingredients: ["Gluten-free flour", "Milk", "Eggs", "Maple syrup"],  
        diet: "gluten-free",  
        preparationTime: "15 minutes",  
        servings: 2,  
    },  
    {  
        label: "Vegan Lentil Soup",  
        ingredients: ["Lentils", "Carrots", "Celery", "Vegetable broth"],  
        diet: "vegan",  
        preparationTime: "40 minutes",  
        servings: 4,  
    },  
    {  
        label: "Vegetarian Pizza",  
        ingredients: ["Pizza dough", "Tomato sauce", "Mushrooms", "Cheese"],  
        diet: "vegetarian",  
        preparationTime: "35 minutes",  
        servings: 2,  
    },  
]